{% set version = "0.4.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ellipse
  version: {{ version|replace("-", "_") }}

source:
  fn: ellipse_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ellipse_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ellipse/ellipse_{{ version }}.tar.gz
  sha256: 1a9a9c52195b26c2b4d51ad159ab98aff7aa8ca25fdc6b2198818d1a0adb023d

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('ellipse')"  # [not win]
    - "\"%R%\" -e \"library('ellipse')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ellipse
  license: GPL (>= 2)
  summary: This package contains various routines for drawing ellipses and ellipse-like confidence
    regions, implementing the plots described in Murdoch and Chow (1996), A graphical
    display of large correlation matrices, The American Statistician 50, 178-180. There
    are also routines implementing the profile plots described in Bates and Watts (1988),
    Nonlinear Regression Analysis and its Applications.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
