travis:
  secure:
    BINSTAR_TOKEN: wOsRQcKPIEJu8i4suhOfuR67kAbPm1ORUBmH9JjwDaC2yU1jrf6mYRaNd5TlQc0SaqyO1fwOt/y6Ld6qR/oQE1BpQaxKg34Chdg/6a/eTTTdxiXq1qG3EiRaJeTtcqGesYX8uLwrMM+yEzTKu4DCRJj0YSB54srniH0quZ/2dWWZ8sVKXb2Pg35XkjwOMSTBJJvqTThBuXJ7yhUDM5RJJ24fKqmMQBihRPkkVWk5cPJ7OS0bEgrtaYg0VzFbFHB0NCP+WmvSRFxFw1vjgdXpxRrhJOL3dhzl7Ov2FdjbR2IbWWsasiFmlTpPA6bFqspAvGWntIlxN9CW47LqXfcX3Mz3CvqzI1ajyG/UiRl2KU1/jsc4gSpFBLBROdRcnx3mKDjpqcqYc4yVQF061O+5V+uOUJTWPfATX8rMddTtHdkWeT61UxJc84RGeSh6DLwJT28707fity954d6iEhQcNMQAiuMukT/jKFfjor5G16kCLaL0TzH1hHn/Olof/qbpiiKim1RAzz8vvisUol5volvdTpTvRShqUatIkyMeJaRVRfUfqxGHn3ynD57DwgRkl+ox0LExCdrxfbv6P9makHlVNcjAh/w4fNn0gSc7K8CmlI4vu4wAxpoJKiXUdpkfWb8sEWHpoTuA/bwWbov3vzl50iPp9FU78VIXwzrLqYw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
