travis:
  secure:
    BINSTAR_TOKEN: ERQit8PqhIEHE6w2RzAOPEduKOHpis9YY0KdNEHssi+Rb/aC8lRWJBod1kI7nelodnYtoUd1QKjuP48Z9r70Zs06ST+7d5Hiztyh9Nm7+0yIwphiW+BKrLw1edHoPqCArOdwbQE7+h4Ocez2epP27WZZt29+uwV4AHB5WmzmlhsBakSDnVfLMyWdjtIcB0kPEdlVvfkjVJ6GTUb0ODHMiKe7BSImPd9kjCJwLDm0nPhDPbI5azCM0Bh0eWzkd/fD/n9A2UZ5RtajJkr+cJrS2WHfDHstB++FNJxwKkcTJl7+WK3exTaUlq7Fs+eZ7t08QMDGcEE7kKenFKr6BKTxrYu1oqvUK3Wcb+d9XZME7isBgYTo3Yq4A8YWC26WkaHhEcurAOtJpdD7sUrH3ygM+WbCsB+4CnlV3rj72Oa7x/tmk3wGLVQtq4BtTlrGUQVpDjLFyWITniWt/Kf/B20vXFfCqvJfdc4ILCFsiTNIMsDqU0ZR4XgjPoCUVkTZuozygdvcj192wGV+nFjZHqrA3g1Z0msBIR8ciYE4Uy7/zY4XWFzljp+K1KslGL415ID06Mx7lMWRQqf+A6WNm4LO2ZtVgaElA8U3vM7ZwR1Xv8WxvhprNOGVcluoBlzrUaEHJDxxM8FN/7/MzMcIpS7J0ggf1nVD4Erp0mIK+ElT44c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
