travis:
  secure:
    BINSTAR_TOKEN: c5Uwu9/qvnTp7Cx/fi3OgyM/wlscRUBvg6sAL+RSji4ZNdGK6wwSZnf69l9KZDKuSIRyOsNT2tgpZS41ME8SFR7pqwGWZoJMHvV+X53hmWkodYq2GEJhBGq84glJvuraem6wWNucqYa6AdY716TssnKAtKbDcD7lL4IiQEhQI9UcXED7A2yqC6BtCNKCvqcwokf5TYjoI2OXjNJpPew5Zdha8vuVpQ8hi/5pksd2thiCo/pA28fCT1zh1HnBelrPSYUUGu2Z92mNWhwwRsdoP0ys/1gb8bc6sLuC5MrcxnLdDQmu1sBGe9bberMq95a/a+nVnzzWJNuWBJ0ZiBmtucXo6AC1fjb5lNMi/tuL2L+rnpFHsSVwpcDr1bw4RrEOc3JkqwjqvtRtKi8X5uFaohoSQzXKo1hidD5J0LNPRGoylt2Vxc0FlpuQrfEuQGdQpYw2Y+0FFirjoL96a7rqeSXQnFQHZlp3cHxoetxPom+i9rHIBrFCbhQUZccSDMVB9gOchfTVbQ2kW2al119nZalm8mLn40n/CMAC8dRyhJFmydQYrzNtTKtwYj/4H7RdeBWJ1aYiGw6tdTDdd1DkaunQT+1KmILYNtjimjku27WacQUShAKzzQMpHuYpi4KwFkrtOubGgsHsxhI0UwiNCl+4XLnwIGoeeGs98ZxAzTA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
