appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FIhFSM/U7VIb3qodJzaxYRl9Ot9Lwg5XwjsfGxLeN9Qc+5fPC/jKZsIdYmCJnKAAnbcLxfKb9el2wWg7JYaRRJ//yOgcCjAgceQK1gR/dGiAotEMWPuiMlXPvxGAZ9Kt340Qvq1ykIDtPOrFA3MlyAE3FT4J/uCTzgpnMEtdTZPLS5EZSQv3iYRZdom4noBJAI66fPX/skst00nSf48Xi74bZd6drEyvqxOuFuavSArbdvOo7+es+weEck2h5AQap5P+XgkRaQgedPaPpgIEoQJIeeLOSHSl9xodI1JhtdhNBYFB69n9quWBPGDItUPKK45WveV4CiSvYAuzuSBdvsCTt5VPy1UcegfkD6+t/b6Ln42qMs6lCZBz7k5PafAmmpIN/ZMfP+xW6KwajVzr/5R0hiOft8BnJlB+y/JqIAjY5ZfhyBd3DoD3SrhCRFDc8ay/jfob4lKSL7gXTs/an5Wevg7TdiiH5J9fg/2ZRhVk0zdRiKpxQIRPQrq4FjZnztaGZncnd2TCNkLdXA39fLmsekRdfcLEB766FJZapnbkL+out6VyJ1nv9GowwwDUtcWGfVQlCsnPG1tDO5AzU1gKvjjnDYWM//d2J9Yf9H4w2khu+LqzvAkACA3uBnkMCBFRfB4evY43iBZxtqq1zz981QR6RtXeoUHv3Z93jQE=}
