travis:
  secure:
    BINSTAR_TOKEN: QNTWHToGswATJVBg4qtS3rHI3OlKLc5OOzmdIrRT6/4dUzFhjyRnnw2R3zn4fsg8yArhVr7Tn8yh0QECY//kmPX4AHmvua8B3frUZUrQ2I1JCou/MwHrhxwdUHmt0lw5mwTDe+r4c/WqVEfyhjCOA1Y9x6jP/+gvxtUeZm2nRoGYYSKyQkj3Fky4fHzsccrNa9gkB3EQbsS2VKg4n4cvfy/CiazzSoUiho4LvO/y4r4kqUF2Cuiwi+hHrqjyc7l/woo5kqEbi9lpWuL0J+k2VMzlRT4Gq2D0WtkYGCqxF8Q82m9TDfUys6dKiKLs1aXKv1ct3+XMLXDF1IdkQ14D34fuhiqrFJ3htgv8yG5jsYQ+82Arxy9SsftYbt9vLptTkJY18ISxJoU6y1AQKxkNA6ZS263SNYR6fDJM3rDRXnD9+2t1QkO1viIM9jJx/8+l50NpxH3g8Op5+pJAO6VaLf0Av1gqAmaQW/ELGtUfRYduVKx8zZy/ct7sRKcaDmuwOu4ice19VyxHdake7LI207WNg8qwfzxkQeVjUAEaJlnV3lgmrZZ9USp/cqzS4WauZs623drkqqT62JUa3+TGH/btl9FDSZAF4xj6n3GJ5kFhaM3+F1Zb+JypbWx4d82USq7NKDlyV4EuZPAJMvixi0vJbUghZtaqu5vlghD9uH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
