travis:
  secure:
    BINSTAR_TOKEN: QsID6hd3CuATyQKc1F65vkKmlqYbaKi+F0DYcJhYsClbp6gXTdxTosgHEb7JZ6WKCTLHhVLlvhZT383MZuVcNs+yBkARvSdXRFmIyFNTp9wNGoawZ81avr92JlipAnVhfzkUBSDbLv8ui5DWrFNwL6uJlfZN4s9pj4hbqtWqxySqY8PLOrlprKFS4NpUMnaXSb5v3CWisFNOP0qUGlVA0QaQOE3YQWCpej/HDiA5tr8gZO+iHVKx4LnCicp3yM/xdE5dmE3fYy/Z+rcLW1JqoWlnkk5N/Nj2zybrzfPbuMJbettBTX7x8gxWOZrDQFO2XxcGnTMbFvMm7xdJEjdpmOSMLS/IH5VPTkCQksjeTDcd5XxHqIHOaTLSZUNlMBa1kCdnF47AWQeMXQRuwGKo9FK7W0yx93tlG1WeRXoft0VOB14Q4F4VGOtYE1HZ1a3Yv+vPeyIove77ofJCWgpKH5YI2MY4QlU+kk3vBxUjmiFZ2gohlQiKkU4wZRRDjnXXQlWLYMyr9RXtT7iqywj3vR/WHwESwBgnd/uBdWndSMrpELrw8cF/EfebWkYg8SJqX5RTOG0jqZ5ZAPtA+sdYCG3DjXo5PQLQ3XcfXhz082WuUPohUwV35IYiB1bJdIb6xugJ7RDb02oAWUhR88fNPBJxftWnzI+CphB4KQ3kYQM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
